baseurl = "https://ditheringdata.netlify.com/"
title = "m.evans"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Michelle Evans"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$","_cache$"]

[Author]
    name = "Michelle Evans"
    profile = "https://mvevans89.github.io/"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Dithering Data"
    description = "Hacky solutions to common data manipulation and mapping problems in R"
    github = "https://github.com/mvevans89"
    twitter = "https://twitter.com/mv_evans"
    stackoverflow = "https://stackoverflow.com/users/5688284/michelle-evans"
    email = "mv.evans.phd@gmail.com"
    opengraph = false
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Topics"
    url = "/tags/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
